name: mdm
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - beautifulsoup4=4.11.1
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - ca-certificates
  - catalogue=2.0.8
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography
  - cudatoolkit=11.0
  - cycler
  - cymem
  - dbus
  - expat
  - fftw
  - filelock
  - fontconfig
  - freetype
  - gdown
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - idna
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - langcodes
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libxcb
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl
  - packaging
  - pathy
  - pcre
  - pillow
  - pip
  - pycparser
  - pydantic
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python-dateutil
  - python_abi=3.8
  - pytorch=1.7.1
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - shellingham
  - sip
  - six
  - smart_open
  - soupsieve
  - spacy=3.3.1
  - spacy-legacy
  - spacy-loggers
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - trimesh
  - typer
  - wandb
  - wheel
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
      - blis==0.7.8
      - chumpy==0.70
      - click==8.1.3
      - confection==0.0.2
      - ftfy==6.1.1
      - importlib-metadata==5.0.0
      - lxml==4.9.1
      - murmurhash==1.0.8
      - preshed==3.0.7
      - pycryptodomex==3.15.0
      - regex==2022.9.13
      - smplx==0.1.28
      - srsly==2.4.4
      - thinc==8.0.17
      - typing-extensions==4.1.1
      - urllib3==1.26.12
      - wasabi==0.10.1
      - wcwidth==0.2.5
      - e3nn==0.4.4